# Generated by Django 4.1.3 on 2022-11-14 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stibapp', '0002_alter_admin_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='pseudo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stibapp.user'),
        ),
    ]
