# Generated by Django 4.1.3 on 2022-11-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stibapp', '0003_alter_admin_pseudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('TRAM', 'Tram'), ('BUS', 'Bus'), ('METRO', 'Metro')], max_length=5)),
            ],
        ),
    ]
