# Generated by Django 4.1.3 on 2022-11-18 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stibapp', '0005_remove_station_category_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='stations',
        ),
        migrations.CreateModel(
            name='StationOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stibapp.line')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stibapp.station')),
            ],
        ),
    ]
